CREATE DATABASE Exercicio_1_3;

USE Exercicio_1_3;

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(50) NOT NULL,
)

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
	Nome VARCHAR(50) NOT NULL,
	CRMV CHAR (12),
)

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
)

CREATE TABLE TipoPet
(
	IdTipopet INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(50) NOT NULL,
)

CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(50) NOT NULL,
)

CREATE TABLE Pet
(
	IdPet INT PRIMARY KEY IDENTITY,
	IdTipopet INT FOREIGN KEY REFERENCES TipoPet(IdTipopet),
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
	Nome VARCHAR(50) NOT NULL,
	DataNascimento CHAR(10) NOT NULL,
)

CREATE TABLE Atendimentos
(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
	Descricao VARCHAR(50) NOT NULL,
	Data CHAR(10) NOT NULL,
)