CREATE DATABASE Exercicio_1_4;

USE Exercicio_1_4;

CREATE TABLE Artistas
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
)

CREATE TABLE Albuns
(
	IdAlbuns INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artistas(IdArtista),
	Titulo VARCHAR(50) NOT NULL,
	DataLancamento VARCHAR(50) NOT NULL,
	Localizacao VARCHAR(50) NOT NULL,
	QtdMinutos SMALLINT NOT NULL,
	Ativo VARCHAR(20) NOT NULL,
)

CREATE TABLE Estilos
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
)

CREATE TABLE AlubunsEstilos
(
	IdAlbuns INT FOREIGN KEY REFERENCES Albuns(IdAlbuns),
	IdEstilos INT FOREIGN KEY REFERENCES Estilos(IdEstilos),
)

CREATE TABLE Usuarios
(
	IdUsuarios INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Senha VARCHAR(30) NOT NULL,
	Permissao VARCHAR(30) NOT NULL,
)